/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "fifo.v:2.1-54.10" *)
module sync_fifo(clk, rst_n, wr_en, rd_en, data_in, data_out, full, empty);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  (* src = "fifo.v:3.13-3.16" *)
  input clk;
  wire clk;
  (* src = "fifo.v:19.18-19.23" *)
  wire [4:0] count;
  (* src = "fifo.v:7.20-7.27" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "fifo.v:8.20-8.28" *)
  output [7:0] data_out;
  wire [7:0] data_out;
  (* src = "fifo.v:10.13-10.18" *)
  output empty;
  wire empty;
  (* src = "fifo.v:9.13-9.17" *)
  output full;
  wire full;
  wire [7:0] \mem[0] ;
  wire [7:0] \mem[10] ;
  wire [7:0] \mem[11] ;
  wire [7:0] \mem[12] ;
  wire [7:0] \mem[13] ;
  wire [7:0] \mem[14] ;
  wire [7:0] \mem[15] ;
  wire [7:0] \mem[1] ;
  wire [7:0] \mem[2] ;
  wire [7:0] \mem[3] ;
  wire [7:0] \mem[4] ;
  wire [7:0] \mem[5] ;
  wire [7:0] \mem[6] ;
  wire [7:0] \mem[7] ;
  wire [7:0] \mem[8] ;
  wire [7:0] \mem[9] ;
  (* src = "fifo.v:6.13-6.18" *)
  input rd_en;
  wire rd_en;
  (* src = "fifo.v:18.26-18.32" *)
  wire [3:0] rd_ptr;
  (* src = "fifo.v:4.13-4.18" *)
  input rst_n;
  wire rst_n;
  (* src = "fifo.v:5.13-5.18" *)
  input wr_en;
  wire wr_en;
  (* src = "fifo.v:18.18-18.24" *)
  wire [3:0] wr_ptr;
  sky130_fd_sc_hdll__clkinv_12 _353_ (
    .A(count[4]),
    .Y(_149_)
  );
  sky130_fd_sc_hdll__clkinv_12 _354_ (
    .A(wr_ptr[3]),
    .Y(_150_)
  );
  sky130_fd_sc_hdll__nor4_6 _355_ (
    .A(count[3]),
    .B(count[2]),
    .C(count[1]),
    .D(count[0]),
    .Y(_151_)
  );
  sky130_fd_sc_hdll__or4_1 _356_ (
    .A(count[3]),
    .B(count[2]),
    .C(count[1]),
    .D(count[0]),
    .X(_152_)
  );
  sky130_fd_sc_hdll__nor2_1 _357_ (
    .A(count[4]),
    .B(_152_),
    .Y(empty)
  );
  sky130_fd_sc_hdll__nor2_1 _358_ (
    .A(_149_),
    .B(_152_),
    .Y(full)
  );
  sky130_fd_sc_hdll__a21boi_1 _359_ (
    .A1(count[4]),
    .A2(_151_),
    .B1_N(wr_en),
    .Y(_153_)
  );
  sky130_fd_sc_hdll__o21ai_1 _360_ (
    .A1(_149_),
    .A2(_152_),
    .B1(wr_en),
    .Y(_154_)
  );
  sky130_fd_sc_hdll__and2_1 _361_ (
    .A(rst_n),
    .B(_153_),
    .X(_155_)
  );
  sky130_fd_sc_hdll__nand2_12 _362_ (
    .A(rst_n),
    .B(_153_),
    .Y(_156_)
  );
  sky130_fd_sc_hdll__nand3_1 _363_ (
    .A(_150_),
    .B(wr_ptr[2]),
    .C(_155_),
    .Y(_157_)
  );
  sky130_fd_sc_hdll__nor3b_1 _364_ (
    .A(_157_),
    .B(wr_ptr[1]),
    .C_N(wr_ptr[0]),
    .Y(_158_)
  );
  sky130_fd_sc_hdll__mux2_12 _365_ (
    .A0(\mem[5] [0]),
    .A1(data_in[0]),
    .S(_158_),
    .X(_000_)
  );
  sky130_fd_sc_hdll__mux2_12 _366_ (
    .A0(\mem[5] [1]),
    .A1(data_in[1]),
    .S(_158_),
    .X(_001_)
  );
  sky130_fd_sc_hdll__mux2_12 _367_ (
    .A0(\mem[5] [2]),
    .A1(data_in[2]),
    .S(_158_),
    .X(_002_)
  );
  sky130_fd_sc_hdll__mux2_12 _368_ (
    .A0(\mem[5] [3]),
    .A1(data_in[3]),
    .S(_158_),
    .X(_003_)
  );
  sky130_fd_sc_hdll__mux2_12 _369_ (
    .A0(\mem[5] [4]),
    .A1(data_in[4]),
    .S(_158_),
    .X(_004_)
  );
  sky130_fd_sc_hdll__mux2_12 _370_ (
    .A0(\mem[5] [5]),
    .A1(data_in[5]),
    .S(_158_),
    .X(_005_)
  );
  sky130_fd_sc_hdll__mux2_12 _371_ (
    .A0(\mem[5] [6]),
    .A1(data_in[6]),
    .S(_158_),
    .X(_006_)
  );
  sky130_fd_sc_hdll__mux2_12 _372_ (
    .A0(\mem[5] [7]),
    .A1(data_in[7]),
    .S(_158_),
    .X(_007_)
  );
  sky130_fd_sc_hdll__nand2_12 _373_ (
    .A(wr_ptr[1]),
    .B(wr_ptr[0]),
    .Y(_159_)
  );
  sky130_fd_sc_hdll__nand2_12 _374_ (
    .A(wr_ptr[3]),
    .B(wr_ptr[2]),
    .Y(_160_)
  );
  sky130_fd_sc_hdll__inputiso1p_1 _375_ (
    .A(_156_),
    .SLEEP(_160_),
    .X(_161_)
  );
  sky130_fd_sc_hdll__nor2_1 _376_ (
    .A(_159_),
    .B(_161_),
    .Y(_162_)
  );
  sky130_fd_sc_hdll__mux2_12 _377_ (
    .A0(\mem[15] [0]),
    .A1(data_in[0]),
    .S(_162_),
    .X(_008_)
  );
  sky130_fd_sc_hdll__mux2_12 _378_ (
    .A0(\mem[15] [1]),
    .A1(data_in[1]),
    .S(_162_),
    .X(_009_)
  );
  sky130_fd_sc_hdll__mux2_12 _379_ (
    .A0(\mem[15] [2]),
    .A1(data_in[2]),
    .S(_162_),
    .X(_010_)
  );
  sky130_fd_sc_hdll__mux2_12 _380_ (
    .A0(\mem[15] [3]),
    .A1(data_in[3]),
    .S(_162_),
    .X(_011_)
  );
  sky130_fd_sc_hdll__mux2_12 _381_ (
    .A0(\mem[15] [4]),
    .A1(data_in[4]),
    .S(_162_),
    .X(_012_)
  );
  sky130_fd_sc_hdll__mux2_12 _382_ (
    .A0(\mem[15] [5]),
    .A1(data_in[5]),
    .S(_162_),
    .X(_013_)
  );
  sky130_fd_sc_hdll__mux2_12 _383_ (
    .A0(\mem[15] [6]),
    .A1(data_in[6]),
    .S(_162_),
    .X(_014_)
  );
  sky130_fd_sc_hdll__mux2_12 _384_ (
    .A0(\mem[15] [7]),
    .A1(data_in[7]),
    .S(_162_),
    .X(_015_)
  );
  sky130_fd_sc_hdll__or3_1 _385_ (
    .A(wr_ptr[1]),
    .B(wr_ptr[0]),
    .C(_157_),
    .X(_163_)
  );
  sky130_fd_sc_hdll__mux2_12 _386_ (
    .A0(data_in[0]),
    .A1(\mem[4] [0]),
    .S(_163_),
    .X(_016_)
  );
  sky130_fd_sc_hdll__mux2_12 _387_ (
    .A0(data_in[1]),
    .A1(\mem[4] [1]),
    .S(_163_),
    .X(_017_)
  );
  sky130_fd_sc_hdll__mux2_12 _388_ (
    .A0(data_in[2]),
    .A1(\mem[4] [2]),
    .S(_163_),
    .X(_018_)
  );
  sky130_fd_sc_hdll__mux2_12 _389_ (
    .A0(data_in[3]),
    .A1(\mem[4] [3]),
    .S(_163_),
    .X(_019_)
  );
  sky130_fd_sc_hdll__mux2_12 _390_ (
    .A0(data_in[4]),
    .A1(\mem[4] [4]),
    .S(_163_),
    .X(_020_)
  );
  sky130_fd_sc_hdll__mux2_12 _391_ (
    .A0(data_in[5]),
    .A1(\mem[4] [5]),
    .S(_163_),
    .X(_021_)
  );
  sky130_fd_sc_hdll__mux2_12 _392_ (
    .A0(data_in[6]),
    .A1(\mem[4] [6]),
    .S(_163_),
    .X(_022_)
  );
  sky130_fd_sc_hdll__mux2_12 _393_ (
    .A0(data_in[7]),
    .A1(\mem[4] [7]),
    .S(_163_),
    .X(_023_)
  );
  sky130_fd_sc_hdll__nor4_6 _394_ (
    .A(_150_),
    .B(wr_ptr[2]),
    .C(_156_),
    .D(_159_),
    .Y(_164_)
  );
  sky130_fd_sc_hdll__mux2_12 _395_ (
    .A0(\mem[11] [0]),
    .A1(data_in[0]),
    .S(_164_),
    .X(_024_)
  );
  sky130_fd_sc_hdll__mux2_12 _396_ (
    .A0(\mem[11] [1]),
    .A1(data_in[1]),
    .S(_164_),
    .X(_025_)
  );
  sky130_fd_sc_hdll__mux2_12 _397_ (
    .A0(\mem[11] [2]),
    .A1(data_in[2]),
    .S(_164_),
    .X(_026_)
  );
  sky130_fd_sc_hdll__mux2_12 _398_ (
    .A0(\mem[11] [3]),
    .A1(data_in[3]),
    .S(_164_),
    .X(_027_)
  );
  sky130_fd_sc_hdll__mux2_12 _399_ (
    .A0(\mem[11] [4]),
    .A1(data_in[4]),
    .S(_164_),
    .X(_028_)
  );
  sky130_fd_sc_hdll__mux2_12 _400_ (
    .A0(\mem[11] [5]),
    .A1(data_in[5]),
    .S(_164_),
    .X(_029_)
  );
  sky130_fd_sc_hdll__mux2_12 _401_ (
    .A0(\mem[11] [6]),
    .A1(data_in[6]),
    .S(_164_),
    .X(_030_)
  );
  sky130_fd_sc_hdll__mux2_12 _402_ (
    .A0(\mem[11] [7]),
    .A1(data_in[7]),
    .S(_164_),
    .X(_031_)
  );
  sky130_fd_sc_hdll__nor4_6 _403_ (
    .A(wr_ptr[1]),
    .B(wr_ptr[0]),
    .C(_156_),
    .D(_160_),
    .Y(_165_)
  );
  sky130_fd_sc_hdll__mux2_12 _404_ (
    .A0(\mem[12] [0]),
    .A1(data_in[0]),
    .S(_165_),
    .X(_032_)
  );
  sky130_fd_sc_hdll__mux2_12 _405_ (
    .A0(\mem[12] [1]),
    .A1(data_in[1]),
    .S(_165_),
    .X(_033_)
  );
  sky130_fd_sc_hdll__mux2_12 _406_ (
    .A0(\mem[12] [2]),
    .A1(data_in[2]),
    .S(_165_),
    .X(_034_)
  );
  sky130_fd_sc_hdll__mux2_12 _407_ (
    .A0(\mem[12] [3]),
    .A1(data_in[3]),
    .S(_165_),
    .X(_035_)
  );
  sky130_fd_sc_hdll__mux2_12 _408_ (
    .A0(\mem[12] [4]),
    .A1(data_in[4]),
    .S(_165_),
    .X(_036_)
  );
  sky130_fd_sc_hdll__mux2_12 _409_ (
    .A0(\mem[12] [5]),
    .A1(data_in[5]),
    .S(_165_),
    .X(_037_)
  );
  sky130_fd_sc_hdll__mux2_12 _410_ (
    .A0(\mem[12] [6]),
    .A1(data_in[6]),
    .S(_165_),
    .X(_038_)
  );
  sky130_fd_sc_hdll__mux2_12 _411_ (
    .A0(\mem[12] [7]),
    .A1(data_in[7]),
    .S(_165_),
    .X(_039_)
  );
  sky130_fd_sc_hdll__a21boi_1 _412_ (
    .A1(_149_),
    .A2(_151_),
    .B1_N(rd_en),
    .Y(_166_)
  );
  sky130_fd_sc_hdll__o21ai_1 _413_ (
    .A1(count[4]),
    .A2(_152_),
    .B1(rd_en),
    .Y(_167_)
  );
  sky130_fd_sc_hdll__mux2i_1 _414_ (
    .A0(\mem[12] [0]),
    .A1(\mem[13] [0]),
    .S(rd_ptr[0]),
    .Y(_168_)
  );
  sky130_fd_sc_hdll__isobufsrc_1 _415_ (
    .A(rd_ptr[1]),
    .SLEEP(rd_ptr[0]),
    .X(_169_)
  );
  sky130_fd_sc_hdll__and2_1 _416_ (
    .A(rd_ptr[1]),
    .B(rd_ptr[0]),
    .X(_170_)
  );
  sky130_fd_sc_hdll__a22oi_1 _417_ (
    .A1(\mem[14] [0]),
    .A2(_169_),
    .B1(_170_),
    .B2(\mem[15] [0]),
    .Y(_171_)
  );
  sky130_fd_sc_hdll__o211ai_1 _418_ (
    .A1(rd_ptr[1]),
    .A2(_168_),
    .B1(_171_),
    .C1(rd_ptr[2]),
    .Y(_172_)
  );
  sky130_fd_sc_hdll__mux2i_1 _419_ (
    .A0(\mem[8] [0]),
    .A1(\mem[9] [0]),
    .S(rd_ptr[0]),
    .Y(_173_)
  );
  sky130_fd_sc_hdll__a221oi_1 _420_ (
    .A1(\mem[10] [0]),
    .A2(_169_),
    .B1(_170_),
    .B2(\mem[11] [0]),
    .C1(rd_ptr[2]),
    .Y(_174_)
  );
  sky130_fd_sc_hdll__o21ai_1 _421_ (
    .A1(rd_ptr[1]),
    .A2(_173_),
    .B1(_174_),
    .Y(_175_)
  );
  sky130_fd_sc_hdll__nand2_12 _422_ (
    .A(_172_),
    .B(_175_),
    .Y(_176_)
  );
  sky130_fd_sc_hdll__mux2i_1 _423_ (
    .A0(\mem[4] [0]),
    .A1(\mem[5] [0]),
    .S(rd_ptr[0]),
    .Y(_177_)
  );
  sky130_fd_sc_hdll__a22oi_1 _424_ (
    .A1(\mem[6] [0]),
    .A2(_169_),
    .B1(_170_),
    .B2(\mem[7] [0]),
    .Y(_178_)
  );
  sky130_fd_sc_hdll__o211ai_1 _425_ (
    .A1(rd_ptr[1]),
    .A2(_177_),
    .B1(_178_),
    .C1(rd_ptr[2]),
    .Y(_179_)
  );
  sky130_fd_sc_hdll__mux2i_1 _426_ (
    .A0(\mem[0] [0]),
    .A1(\mem[1] [0]),
    .S(rd_ptr[0]),
    .Y(_180_)
  );
  sky130_fd_sc_hdll__a221oi_1 _427_ (
    .A1(\mem[2] [0]),
    .A2(_169_),
    .B1(_170_),
    .B2(\mem[3] [0]),
    .C1(rd_ptr[2]),
    .Y(_181_)
  );
  sky130_fd_sc_hdll__o21ai_1 _428_ (
    .A1(rd_ptr[1]),
    .A2(_180_),
    .B1(_181_),
    .Y(_182_)
  );
  sky130_fd_sc_hdll__a21oi_1 _429_ (
    .A1(_179_),
    .A2(_182_),
    .B1(rd_ptr[3]),
    .Y(_183_)
  );
  sky130_fd_sc_hdll__a21o_6 _430_ (
    .A1(rd_ptr[3]),
    .A2(_176_),
    .B1(_183_),
    .X(_184_)
  );
  sky130_fd_sc_hdll__o21ai_1 _431_ (
    .A1(data_out[0]),
    .A2(_166_),
    .B1(rst_n),
    .Y(_185_)
  );
  sky130_fd_sc_hdll__a21oi_1 _432_ (
    .A1(_166_),
    .A2(_184_),
    .B1(_185_),
    .Y(_040_)
  );
  sky130_fd_sc_hdll__mux2i_1 _433_ (
    .A0(\mem[12] [1]),
    .A1(\mem[13] [1]),
    .S(rd_ptr[0]),
    .Y(_186_)
  );
  sky130_fd_sc_hdll__a22oi_1 _434_ (
    .A1(\mem[14] [1]),
    .A2(_169_),
    .B1(_170_),
    .B2(\mem[15] [1]),
    .Y(_187_)
  );
  sky130_fd_sc_hdll__o211ai_1 _435_ (
    .A1(rd_ptr[1]),
    .A2(_186_),
    .B1(_187_),
    .C1(rd_ptr[2]),
    .Y(_188_)
  );
  sky130_fd_sc_hdll__mux2i_1 _436_ (
    .A0(\mem[8] [1]),
    .A1(\mem[9] [1]),
    .S(rd_ptr[0]),
    .Y(_189_)
  );
  sky130_fd_sc_hdll__a221oi_1 _437_ (
    .A1(\mem[10] [1]),
    .A2(_169_),
    .B1(_170_),
    .B2(\mem[11] [1]),
    .C1(rd_ptr[2]),
    .Y(_190_)
  );
  sky130_fd_sc_hdll__o21ai_1 _438_ (
    .A1(rd_ptr[1]),
    .A2(_189_),
    .B1(_190_),
    .Y(_191_)
  );
  sky130_fd_sc_hdll__nand2_12 _439_ (
    .A(_188_),
    .B(_191_),
    .Y(_192_)
  );
  sky130_fd_sc_hdll__mux2i_1 _440_ (
    .A0(\mem[4] [1]),
    .A1(\mem[5] [1]),
    .S(rd_ptr[0]),
    .Y(_193_)
  );
  sky130_fd_sc_hdll__a22oi_1 _441_ (
    .A1(\mem[6] [1]),
    .A2(_169_),
    .B1(_170_),
    .B2(\mem[7] [1]),
    .Y(_194_)
  );
  sky130_fd_sc_hdll__o211ai_1 _442_ (
    .A1(rd_ptr[1]),
    .A2(_193_),
    .B1(_194_),
    .C1(rd_ptr[2]),
    .Y(_195_)
  );
  sky130_fd_sc_hdll__mux2i_1 _443_ (
    .A0(\mem[0] [1]),
    .A1(\mem[1] [1]),
    .S(rd_ptr[0]),
    .Y(_196_)
  );
  sky130_fd_sc_hdll__a221oi_1 _444_ (
    .A1(\mem[2] [1]),
    .A2(_169_),
    .B1(_170_),
    .B2(\mem[3] [1]),
    .C1(rd_ptr[2]),
    .Y(_197_)
  );
  sky130_fd_sc_hdll__o21ai_1 _445_ (
    .A1(rd_ptr[1]),
    .A2(_196_),
    .B1(_197_),
    .Y(_198_)
  );
  sky130_fd_sc_hdll__a21oi_1 _446_ (
    .A1(_195_),
    .A2(_198_),
    .B1(rd_ptr[3]),
    .Y(_199_)
  );
  sky130_fd_sc_hdll__a21o_6 _447_ (
    .A1(rd_ptr[3]),
    .A2(_192_),
    .B1(_199_),
    .X(_200_)
  );
  sky130_fd_sc_hdll__o21ai_1 _448_ (
    .A1(data_out[1]),
    .A2(_166_),
    .B1(rst_n),
    .Y(_201_)
  );
  sky130_fd_sc_hdll__a21oi_1 _449_ (
    .A1(_166_),
    .A2(_200_),
    .B1(_201_),
    .Y(_041_)
  );
  sky130_fd_sc_hdll__mux2i_1 _450_ (
    .A0(\mem[12] [2]),
    .A1(\mem[13] [2]),
    .S(rd_ptr[0]),
    .Y(_202_)
  );
  sky130_fd_sc_hdll__a22oi_1 _451_ (
    .A1(\mem[14] [2]),
    .A2(_169_),
    .B1(_170_),
    .B2(\mem[15] [2]),
    .Y(_203_)
  );
  sky130_fd_sc_hdll__o211ai_1 _452_ (
    .A1(rd_ptr[1]),
    .A2(_202_),
    .B1(_203_),
    .C1(rd_ptr[2]),
    .Y(_204_)
  );
  sky130_fd_sc_hdll__mux2i_1 _453_ (
    .A0(\mem[8] [2]),
    .A1(\mem[9] [2]),
    .S(rd_ptr[0]),
    .Y(_205_)
  );
  sky130_fd_sc_hdll__a221oi_1 _454_ (
    .A1(\mem[10] [2]),
    .A2(_169_),
    .B1(_170_),
    .B2(\mem[11] [2]),
    .C1(rd_ptr[2]),
    .Y(_206_)
  );
  sky130_fd_sc_hdll__o21ai_1 _455_ (
    .A1(rd_ptr[1]),
    .A2(_205_),
    .B1(_206_),
    .Y(_207_)
  );
  sky130_fd_sc_hdll__nand2_12 _456_ (
    .A(_204_),
    .B(_207_),
    .Y(_208_)
  );
  sky130_fd_sc_hdll__mux2i_1 _457_ (
    .A0(\mem[4] [2]),
    .A1(\mem[5] [2]),
    .S(rd_ptr[0]),
    .Y(_209_)
  );
  sky130_fd_sc_hdll__a22oi_1 _458_ (
    .A1(\mem[6] [2]),
    .A2(_169_),
    .B1(_170_),
    .B2(\mem[7] [2]),
    .Y(_210_)
  );
  sky130_fd_sc_hdll__o211ai_1 _459_ (
    .A1(rd_ptr[1]),
    .A2(_209_),
    .B1(_210_),
    .C1(rd_ptr[2]),
    .Y(_211_)
  );
  sky130_fd_sc_hdll__mux2i_1 _460_ (
    .A0(\mem[0] [2]),
    .A1(\mem[1] [2]),
    .S(rd_ptr[0]),
    .Y(_212_)
  );
  sky130_fd_sc_hdll__a221oi_1 _461_ (
    .A1(\mem[2] [2]),
    .A2(_169_),
    .B1(_170_),
    .B2(\mem[3] [2]),
    .C1(rd_ptr[2]),
    .Y(_213_)
  );
  sky130_fd_sc_hdll__o21ai_1 _462_ (
    .A1(rd_ptr[1]),
    .A2(_212_),
    .B1(_213_),
    .Y(_214_)
  );
  sky130_fd_sc_hdll__a21oi_1 _463_ (
    .A1(_211_),
    .A2(_214_),
    .B1(rd_ptr[3]),
    .Y(_215_)
  );
  sky130_fd_sc_hdll__a21o_6 _464_ (
    .A1(rd_ptr[3]),
    .A2(_208_),
    .B1(_215_),
    .X(_216_)
  );
  sky130_fd_sc_hdll__o21ai_1 _465_ (
    .A1(data_out[2]),
    .A2(_166_),
    .B1(rst_n),
    .Y(_217_)
  );
  sky130_fd_sc_hdll__a21oi_1 _466_ (
    .A1(_166_),
    .A2(_216_),
    .B1(_217_),
    .Y(_042_)
  );
  sky130_fd_sc_hdll__mux2i_1 _467_ (
    .A0(\mem[12] [3]),
    .A1(\mem[13] [3]),
    .S(rd_ptr[0]),
    .Y(_218_)
  );
  sky130_fd_sc_hdll__a22oi_1 _468_ (
    .A1(\mem[14] [3]),
    .A2(_169_),
    .B1(_170_),
    .B2(\mem[15] [3]),
    .Y(_219_)
  );
  sky130_fd_sc_hdll__o211ai_1 _469_ (
    .A1(rd_ptr[1]),
    .A2(_218_),
    .B1(_219_),
    .C1(rd_ptr[2]),
    .Y(_220_)
  );
  sky130_fd_sc_hdll__mux2i_1 _470_ (
    .A0(\mem[8] [3]),
    .A1(\mem[9] [3]),
    .S(rd_ptr[0]),
    .Y(_221_)
  );
  sky130_fd_sc_hdll__a221oi_1 _471_ (
    .A1(\mem[10] [3]),
    .A2(_169_),
    .B1(_170_),
    .B2(\mem[11] [3]),
    .C1(rd_ptr[2]),
    .Y(_222_)
  );
  sky130_fd_sc_hdll__o21ai_1 _472_ (
    .A1(rd_ptr[1]),
    .A2(_221_),
    .B1(_222_),
    .Y(_223_)
  );
  sky130_fd_sc_hdll__nand2_12 _473_ (
    .A(_220_),
    .B(_223_),
    .Y(_224_)
  );
  sky130_fd_sc_hdll__mux2i_1 _474_ (
    .A0(\mem[4] [3]),
    .A1(\mem[5] [3]),
    .S(rd_ptr[0]),
    .Y(_225_)
  );
  sky130_fd_sc_hdll__a22oi_1 _475_ (
    .A1(\mem[6] [3]),
    .A2(_169_),
    .B1(_170_),
    .B2(\mem[7] [3]),
    .Y(_226_)
  );
  sky130_fd_sc_hdll__o211ai_1 _476_ (
    .A1(rd_ptr[1]),
    .A2(_225_),
    .B1(_226_),
    .C1(rd_ptr[2]),
    .Y(_227_)
  );
  sky130_fd_sc_hdll__mux2i_1 _477_ (
    .A0(\mem[0] [3]),
    .A1(\mem[1] [3]),
    .S(rd_ptr[0]),
    .Y(_228_)
  );
  sky130_fd_sc_hdll__a221oi_1 _478_ (
    .A1(\mem[2] [3]),
    .A2(_169_),
    .B1(_170_),
    .B2(\mem[3] [3]),
    .C1(rd_ptr[2]),
    .Y(_229_)
  );
  sky130_fd_sc_hdll__o21ai_1 _479_ (
    .A1(rd_ptr[1]),
    .A2(_228_),
    .B1(_229_),
    .Y(_230_)
  );
  sky130_fd_sc_hdll__a21oi_1 _480_ (
    .A1(_227_),
    .A2(_230_),
    .B1(rd_ptr[3]),
    .Y(_231_)
  );
  sky130_fd_sc_hdll__a21o_6 _481_ (
    .A1(rd_ptr[3]),
    .A2(_224_),
    .B1(_231_),
    .X(_232_)
  );
  sky130_fd_sc_hdll__o21ai_1 _482_ (
    .A1(data_out[3]),
    .A2(_166_),
    .B1(rst_n),
    .Y(_233_)
  );
  sky130_fd_sc_hdll__a21oi_1 _483_ (
    .A1(_166_),
    .A2(_232_),
    .B1(_233_),
    .Y(_043_)
  );
  sky130_fd_sc_hdll__mux2i_1 _484_ (
    .A0(\mem[12] [4]),
    .A1(\mem[13] [4]),
    .S(rd_ptr[0]),
    .Y(_234_)
  );
  sky130_fd_sc_hdll__a22oi_1 _485_ (
    .A1(\mem[14] [4]),
    .A2(_169_),
    .B1(_170_),
    .B2(\mem[15] [4]),
    .Y(_235_)
  );
  sky130_fd_sc_hdll__o211ai_1 _486_ (
    .A1(rd_ptr[1]),
    .A2(_234_),
    .B1(_235_),
    .C1(rd_ptr[2]),
    .Y(_236_)
  );
  sky130_fd_sc_hdll__mux2i_1 _487_ (
    .A0(\mem[8] [4]),
    .A1(\mem[9] [4]),
    .S(rd_ptr[0]),
    .Y(_237_)
  );
  sky130_fd_sc_hdll__a221oi_1 _488_ (
    .A1(\mem[10] [4]),
    .A2(_169_),
    .B1(_170_),
    .B2(\mem[11] [4]),
    .C1(rd_ptr[2]),
    .Y(_238_)
  );
  sky130_fd_sc_hdll__o21ai_1 _489_ (
    .A1(rd_ptr[1]),
    .A2(_237_),
    .B1(_238_),
    .Y(_239_)
  );
  sky130_fd_sc_hdll__nand2_12 _490_ (
    .A(_236_),
    .B(_239_),
    .Y(_240_)
  );
  sky130_fd_sc_hdll__mux2i_1 _491_ (
    .A0(\mem[4] [4]),
    .A1(\mem[5] [4]),
    .S(rd_ptr[0]),
    .Y(_241_)
  );
  sky130_fd_sc_hdll__a22oi_1 _492_ (
    .A1(\mem[6] [4]),
    .A2(_169_),
    .B1(_170_),
    .B2(\mem[7] [4]),
    .Y(_242_)
  );
  sky130_fd_sc_hdll__o211ai_1 _493_ (
    .A1(rd_ptr[1]),
    .A2(_241_),
    .B1(_242_),
    .C1(rd_ptr[2]),
    .Y(_243_)
  );
  sky130_fd_sc_hdll__mux2i_1 _494_ (
    .A0(\mem[0] [4]),
    .A1(\mem[1] [4]),
    .S(rd_ptr[0]),
    .Y(_244_)
  );
  sky130_fd_sc_hdll__a221oi_1 _495_ (
    .A1(\mem[2] [4]),
    .A2(_169_),
    .B1(_170_),
    .B2(\mem[3] [4]),
    .C1(rd_ptr[2]),
    .Y(_245_)
  );
  sky130_fd_sc_hdll__o21ai_1 _496_ (
    .A1(rd_ptr[1]),
    .A2(_244_),
    .B1(_245_),
    .Y(_246_)
  );
  sky130_fd_sc_hdll__a21oi_1 _497_ (
    .A1(_243_),
    .A2(_246_),
    .B1(rd_ptr[3]),
    .Y(_247_)
  );
  sky130_fd_sc_hdll__a21o_6 _498_ (
    .A1(rd_ptr[3]),
    .A2(_240_),
    .B1(_247_),
    .X(_248_)
  );
  sky130_fd_sc_hdll__o21ai_1 _499_ (
    .A1(data_out[4]),
    .A2(_166_),
    .B1(rst_n),
    .Y(_249_)
  );
  sky130_fd_sc_hdll__a21oi_1 _500_ (
    .A1(_166_),
    .A2(_248_),
    .B1(_249_),
    .Y(_044_)
  );
  sky130_fd_sc_hdll__mux2i_1 _501_ (
    .A0(\mem[12] [5]),
    .A1(\mem[13] [5]),
    .S(rd_ptr[0]),
    .Y(_250_)
  );
  sky130_fd_sc_hdll__a22oi_1 _502_ (
    .A1(\mem[14] [5]),
    .A2(_169_),
    .B1(_170_),
    .B2(\mem[15] [5]),
    .Y(_251_)
  );
  sky130_fd_sc_hdll__o211ai_1 _503_ (
    .A1(rd_ptr[1]),
    .A2(_250_),
    .B1(_251_),
    .C1(rd_ptr[2]),
    .Y(_252_)
  );
  sky130_fd_sc_hdll__mux2i_1 _504_ (
    .A0(\mem[8] [5]),
    .A1(\mem[9] [5]),
    .S(rd_ptr[0]),
    .Y(_253_)
  );
  sky130_fd_sc_hdll__a221oi_1 _505_ (
    .A1(\mem[10] [5]),
    .A2(_169_),
    .B1(_170_),
    .B2(\mem[11] [5]),
    .C1(rd_ptr[2]),
    .Y(_254_)
  );
  sky130_fd_sc_hdll__o21ai_1 _506_ (
    .A1(rd_ptr[1]),
    .A2(_253_),
    .B1(_254_),
    .Y(_255_)
  );
  sky130_fd_sc_hdll__nand2_12 _507_ (
    .A(_252_),
    .B(_255_),
    .Y(_256_)
  );
  sky130_fd_sc_hdll__mux2i_1 _508_ (
    .A0(\mem[4] [5]),
    .A1(\mem[5] [5]),
    .S(rd_ptr[0]),
    .Y(_257_)
  );
  sky130_fd_sc_hdll__a22oi_1 _509_ (
    .A1(\mem[6] [5]),
    .A2(_169_),
    .B1(_170_),
    .B2(\mem[7] [5]),
    .Y(_258_)
  );
  sky130_fd_sc_hdll__o211ai_1 _510_ (
    .A1(rd_ptr[1]),
    .A2(_257_),
    .B1(_258_),
    .C1(rd_ptr[2]),
    .Y(_259_)
  );
  sky130_fd_sc_hdll__mux2i_1 _511_ (
    .A0(\mem[0] [5]),
    .A1(\mem[1] [5]),
    .S(rd_ptr[0]),
    .Y(_260_)
  );
  sky130_fd_sc_hdll__a221oi_1 _512_ (
    .A1(\mem[2] [5]),
    .A2(_169_),
    .B1(_170_),
    .B2(\mem[3] [5]),
    .C1(rd_ptr[2]),
    .Y(_261_)
  );
  sky130_fd_sc_hdll__o21ai_1 _513_ (
    .A1(rd_ptr[1]),
    .A2(_260_),
    .B1(_261_),
    .Y(_262_)
  );
  sky130_fd_sc_hdll__a21oi_1 _514_ (
    .A1(_259_),
    .A2(_262_),
    .B1(rd_ptr[3]),
    .Y(_263_)
  );
  sky130_fd_sc_hdll__a21o_6 _515_ (
    .A1(rd_ptr[3]),
    .A2(_256_),
    .B1(_263_),
    .X(_264_)
  );
  sky130_fd_sc_hdll__o21ai_1 _516_ (
    .A1(data_out[5]),
    .A2(_166_),
    .B1(rst_n),
    .Y(_265_)
  );
  sky130_fd_sc_hdll__a21oi_1 _517_ (
    .A1(_166_),
    .A2(_264_),
    .B1(_265_),
    .Y(_045_)
  );
  sky130_fd_sc_hdll__mux2i_1 _518_ (
    .A0(\mem[12] [6]),
    .A1(\mem[13] [6]),
    .S(rd_ptr[0]),
    .Y(_266_)
  );
  sky130_fd_sc_hdll__a22oi_1 _519_ (
    .A1(\mem[14] [6]),
    .A2(_169_),
    .B1(_170_),
    .B2(\mem[15] [6]),
    .Y(_267_)
  );
  sky130_fd_sc_hdll__o211ai_1 _520_ (
    .A1(rd_ptr[1]),
    .A2(_266_),
    .B1(_267_),
    .C1(rd_ptr[2]),
    .Y(_268_)
  );
  sky130_fd_sc_hdll__mux2i_1 _521_ (
    .A0(\mem[8] [6]),
    .A1(\mem[9] [6]),
    .S(rd_ptr[0]),
    .Y(_269_)
  );
  sky130_fd_sc_hdll__a221oi_1 _522_ (
    .A1(\mem[10] [6]),
    .A2(_169_),
    .B1(_170_),
    .B2(\mem[11] [6]),
    .C1(rd_ptr[2]),
    .Y(_270_)
  );
  sky130_fd_sc_hdll__o21ai_1 _523_ (
    .A1(rd_ptr[1]),
    .A2(_269_),
    .B1(_270_),
    .Y(_271_)
  );
  sky130_fd_sc_hdll__nand2_12 _524_ (
    .A(_268_),
    .B(_271_),
    .Y(_272_)
  );
  sky130_fd_sc_hdll__mux2i_1 _525_ (
    .A0(\mem[4] [6]),
    .A1(\mem[5] [6]),
    .S(rd_ptr[0]),
    .Y(_273_)
  );
  sky130_fd_sc_hdll__a22oi_1 _526_ (
    .A1(\mem[6] [6]),
    .A2(_169_),
    .B1(_170_),
    .B2(\mem[7] [6]),
    .Y(_274_)
  );
  sky130_fd_sc_hdll__o211ai_1 _527_ (
    .A1(rd_ptr[1]),
    .A2(_273_),
    .B1(_274_),
    .C1(rd_ptr[2]),
    .Y(_275_)
  );
  sky130_fd_sc_hdll__mux2i_1 _528_ (
    .A0(\mem[0] [6]),
    .A1(\mem[1] [6]),
    .S(rd_ptr[0]),
    .Y(_276_)
  );
  sky130_fd_sc_hdll__a221oi_1 _529_ (
    .A1(\mem[2] [6]),
    .A2(_169_),
    .B1(_170_),
    .B2(\mem[3] [6]),
    .C1(rd_ptr[2]),
    .Y(_277_)
  );
  sky130_fd_sc_hdll__o21ai_1 _530_ (
    .A1(rd_ptr[1]),
    .A2(_276_),
    .B1(_277_),
    .Y(_278_)
  );
  sky130_fd_sc_hdll__a21oi_1 _531_ (
    .A1(_275_),
    .A2(_278_),
    .B1(rd_ptr[3]),
    .Y(_279_)
  );
  sky130_fd_sc_hdll__a21o_6 _532_ (
    .A1(rd_ptr[3]),
    .A2(_272_),
    .B1(_279_),
    .X(_280_)
  );
  sky130_fd_sc_hdll__o21ai_1 _533_ (
    .A1(data_out[6]),
    .A2(_166_),
    .B1(rst_n),
    .Y(_281_)
  );
  sky130_fd_sc_hdll__a21oi_1 _534_ (
    .A1(_166_),
    .A2(_280_),
    .B1(_281_),
    .Y(_046_)
  );
  sky130_fd_sc_hdll__mux2i_1 _535_ (
    .A0(\mem[12] [7]),
    .A1(\mem[13] [7]),
    .S(rd_ptr[0]),
    .Y(_282_)
  );
  sky130_fd_sc_hdll__a22oi_1 _536_ (
    .A1(\mem[14] [7]),
    .A2(_169_),
    .B1(_170_),
    .B2(\mem[15] [7]),
    .Y(_283_)
  );
  sky130_fd_sc_hdll__o211ai_1 _537_ (
    .A1(rd_ptr[1]),
    .A2(_282_),
    .B1(_283_),
    .C1(rd_ptr[2]),
    .Y(_284_)
  );
  sky130_fd_sc_hdll__mux2i_1 _538_ (
    .A0(\mem[8] [7]),
    .A1(\mem[9] [7]),
    .S(rd_ptr[0]),
    .Y(_285_)
  );
  sky130_fd_sc_hdll__a221oi_1 _539_ (
    .A1(\mem[10] [7]),
    .A2(_169_),
    .B1(_170_),
    .B2(\mem[11] [7]),
    .C1(rd_ptr[2]),
    .Y(_286_)
  );
  sky130_fd_sc_hdll__o21ai_1 _540_ (
    .A1(rd_ptr[1]),
    .A2(_285_),
    .B1(_286_),
    .Y(_287_)
  );
  sky130_fd_sc_hdll__nand2_12 _541_ (
    .A(_284_),
    .B(_287_),
    .Y(_288_)
  );
  sky130_fd_sc_hdll__mux2i_1 _542_ (
    .A0(\mem[4] [7]),
    .A1(\mem[5] [7]),
    .S(rd_ptr[0]),
    .Y(_289_)
  );
  sky130_fd_sc_hdll__a22oi_1 _543_ (
    .A1(\mem[6] [7]),
    .A2(_169_),
    .B1(_170_),
    .B2(\mem[7] [7]),
    .Y(_290_)
  );
  sky130_fd_sc_hdll__o211ai_1 _544_ (
    .A1(rd_ptr[1]),
    .A2(_289_),
    .B1(_290_),
    .C1(rd_ptr[2]),
    .Y(_291_)
  );
  sky130_fd_sc_hdll__mux2i_1 _545_ (
    .A0(\mem[0] [7]),
    .A1(\mem[1] [7]),
    .S(rd_ptr[0]),
    .Y(_292_)
  );
  sky130_fd_sc_hdll__a221oi_1 _546_ (
    .A1(\mem[2] [7]),
    .A2(_169_),
    .B1(_170_),
    .B2(\mem[3] [7]),
    .C1(rd_ptr[2]),
    .Y(_293_)
  );
  sky130_fd_sc_hdll__o21ai_1 _547_ (
    .A1(rd_ptr[1]),
    .A2(_292_),
    .B1(_293_),
    .Y(_294_)
  );
  sky130_fd_sc_hdll__a21oi_1 _548_ (
    .A1(_291_),
    .A2(_294_),
    .B1(rd_ptr[3]),
    .Y(_295_)
  );
  sky130_fd_sc_hdll__a21o_6 _549_ (
    .A1(rd_ptr[3]),
    .A2(_288_),
    .B1(_295_),
    .X(_296_)
  );
  sky130_fd_sc_hdll__o21ai_1 _550_ (
    .A1(data_out[7]),
    .A2(_166_),
    .B1(rst_n),
    .Y(_297_)
  );
  sky130_fd_sc_hdll__a21oi_1 _551_ (
    .A1(_166_),
    .A2(_296_),
    .B1(_297_),
    .Y(_047_)
  );
  sky130_fd_sc_hdll__nor2_1 _552_ (
    .A(wr_ptr[3]),
    .B(wr_ptr[2]),
    .Y(_298_)
  );
  sky130_fd_sc_hdll__nor4_6 _553_ (
    .A(wr_ptr[3]),
    .B(wr_ptr[2]),
    .C(_156_),
    .D(_159_),
    .Y(_299_)
  );
  sky130_fd_sc_hdll__mux2_12 _554_ (
    .A0(\mem[3] [0]),
    .A1(data_in[0]),
    .S(_299_),
    .X(_048_)
  );
  sky130_fd_sc_hdll__mux2_12 _555_ (
    .A0(\mem[3] [1]),
    .A1(data_in[1]),
    .S(_299_),
    .X(_049_)
  );
  sky130_fd_sc_hdll__mux2_12 _556_ (
    .A0(\mem[3] [2]),
    .A1(data_in[2]),
    .S(_299_),
    .X(_050_)
  );
  sky130_fd_sc_hdll__mux2_12 _557_ (
    .A0(\mem[3] [3]),
    .A1(data_in[3]),
    .S(_299_),
    .X(_051_)
  );
  sky130_fd_sc_hdll__mux2_12 _558_ (
    .A0(\mem[3] [4]),
    .A1(data_in[4]),
    .S(_299_),
    .X(_052_)
  );
  sky130_fd_sc_hdll__mux2_12 _559_ (
    .A0(\mem[3] [5]),
    .A1(data_in[5]),
    .S(_299_),
    .X(_053_)
  );
  sky130_fd_sc_hdll__mux2_12 _560_ (
    .A0(\mem[3] [6]),
    .A1(data_in[6]),
    .S(_299_),
    .X(_054_)
  );
  sky130_fd_sc_hdll__mux2_12 _561_ (
    .A0(\mem[3] [7]),
    .A1(data_in[7]),
    .S(_299_),
    .X(_055_)
  );
  sky130_fd_sc_hdll__nand3b_1 _562_ (
    .A_N(wr_ptr[1]),
    .B(wr_ptr[0]),
    .C(_155_),
    .Y(_300_)
  );
  sky130_fd_sc_hdll__nor2_1 _563_ (
    .A(_160_),
    .B(_300_),
    .Y(_301_)
  );
  sky130_fd_sc_hdll__mux2_12 _564_ (
    .A0(\mem[13] [0]),
    .A1(data_in[0]),
    .S(_301_),
    .X(_056_)
  );
  sky130_fd_sc_hdll__mux2_12 _565_ (
    .A0(\mem[13] [1]),
    .A1(data_in[1]),
    .S(_301_),
    .X(_057_)
  );
  sky130_fd_sc_hdll__mux2_12 _566_ (
    .A0(\mem[13] [2]),
    .A1(data_in[2]),
    .S(_301_),
    .X(_058_)
  );
  sky130_fd_sc_hdll__mux2_12 _567_ (
    .A0(\mem[13] [3]),
    .A1(data_in[3]),
    .S(_301_),
    .X(_059_)
  );
  sky130_fd_sc_hdll__mux2_12 _568_ (
    .A0(\mem[13] [4]),
    .A1(data_in[4]),
    .S(_301_),
    .X(_060_)
  );
  sky130_fd_sc_hdll__mux2_12 _569_ (
    .A0(\mem[13] [5]),
    .A1(data_in[5]),
    .S(_301_),
    .X(_061_)
  );
  sky130_fd_sc_hdll__mux2_12 _570_ (
    .A0(\mem[13] [6]),
    .A1(data_in[6]),
    .S(_301_),
    .X(_062_)
  );
  sky130_fd_sc_hdll__mux2_12 _571_ (
    .A0(\mem[13] [7]),
    .A1(data_in[7]),
    .S(_301_),
    .X(_063_)
  );
  sky130_fd_sc_hdll__nand2b_1 _572_ (
    .A_N(wr_ptr[0]),
    .B(wr_ptr[1]),
    .Y(_302_)
  );
  sky130_fd_sc_hdll__nor2_1 _573_ (
    .A(_161_),
    .B(_302_),
    .Y(_303_)
  );
  sky130_fd_sc_hdll__mux2_12 _574_ (
    .A0(\mem[14] [0]),
    .A1(data_in[0]),
    .S(_303_),
    .X(_064_)
  );
  sky130_fd_sc_hdll__mux2_12 _575_ (
    .A0(\mem[14] [1]),
    .A1(data_in[1]),
    .S(_303_),
    .X(_065_)
  );
  sky130_fd_sc_hdll__mux2_12 _576_ (
    .A0(\mem[14] [2]),
    .A1(data_in[2]),
    .S(_303_),
    .X(_066_)
  );
  sky130_fd_sc_hdll__mux2_12 _577_ (
    .A0(\mem[14] [3]),
    .A1(data_in[3]),
    .S(_303_),
    .X(_067_)
  );
  sky130_fd_sc_hdll__mux2_12 _578_ (
    .A0(\mem[14] [4]),
    .A1(data_in[4]),
    .S(_303_),
    .X(_068_)
  );
  sky130_fd_sc_hdll__mux2_12 _579_ (
    .A0(\mem[14] [5]),
    .A1(data_in[5]),
    .S(_303_),
    .X(_069_)
  );
  sky130_fd_sc_hdll__mux2_12 _580_ (
    .A0(\mem[14] [6]),
    .A1(data_in[6]),
    .S(_303_),
    .X(_070_)
  );
  sky130_fd_sc_hdll__mux2_12 _581_ (
    .A0(\mem[14] [7]),
    .A1(data_in[7]),
    .S(_303_),
    .X(_071_)
  );
  sky130_fd_sc_hdll__or4_1 _582_ (
    .A(wr_ptr[3]),
    .B(wr_ptr[2]),
    .C(_156_),
    .D(_302_),
    .X(_304_)
  );
  sky130_fd_sc_hdll__mux2_12 _583_ (
    .A0(data_in[0]),
    .A1(\mem[2] [0]),
    .S(_304_),
    .X(_072_)
  );
  sky130_fd_sc_hdll__mux2_12 _584_ (
    .A0(data_in[1]),
    .A1(\mem[2] [1]),
    .S(_304_),
    .X(_073_)
  );
  sky130_fd_sc_hdll__mux2_12 _585_ (
    .A0(data_in[2]),
    .A1(\mem[2] [2]),
    .S(_304_),
    .X(_074_)
  );
  sky130_fd_sc_hdll__mux2_12 _586_ (
    .A0(data_in[3]),
    .A1(\mem[2] [3]),
    .S(_304_),
    .X(_075_)
  );
  sky130_fd_sc_hdll__mux2_12 _587_ (
    .A0(data_in[4]),
    .A1(\mem[2] [4]),
    .S(_304_),
    .X(_076_)
  );
  sky130_fd_sc_hdll__mux2_12 _588_ (
    .A0(data_in[5]),
    .A1(\mem[2] [5]),
    .S(_304_),
    .X(_077_)
  );
  sky130_fd_sc_hdll__mux2_12 _589_ (
    .A0(data_in[6]),
    .A1(\mem[2] [6]),
    .S(_304_),
    .X(_078_)
  );
  sky130_fd_sc_hdll__mux2_12 _590_ (
    .A0(data_in[7]),
    .A1(\mem[2] [7]),
    .S(_304_),
    .X(_079_)
  );
  sky130_fd_sc_hdll__nor2_1 _591_ (
    .A(_157_),
    .B(_302_),
    .Y(_305_)
  );
  sky130_fd_sc_hdll__mux2_12 _592_ (
    .A0(\mem[6] [0]),
    .A1(data_in[0]),
    .S(_305_),
    .X(_080_)
  );
  sky130_fd_sc_hdll__mux2_12 _593_ (
    .A0(\mem[6] [1]),
    .A1(data_in[1]),
    .S(_305_),
    .X(_081_)
  );
  sky130_fd_sc_hdll__mux2_12 _594_ (
    .A0(\mem[6] [2]),
    .A1(data_in[2]),
    .S(_305_),
    .X(_082_)
  );
  sky130_fd_sc_hdll__mux2_12 _595_ (
    .A0(\mem[6] [3]),
    .A1(data_in[3]),
    .S(_305_),
    .X(_083_)
  );
  sky130_fd_sc_hdll__mux2_12 _596_ (
    .A0(\mem[6] [4]),
    .A1(data_in[4]),
    .S(_305_),
    .X(_084_)
  );
  sky130_fd_sc_hdll__mux2_12 _597_ (
    .A0(\mem[6] [5]),
    .A1(data_in[5]),
    .S(_305_),
    .X(_085_)
  );
  sky130_fd_sc_hdll__mux2_12 _598_ (
    .A0(\mem[6] [6]),
    .A1(data_in[6]),
    .S(_305_),
    .X(_086_)
  );
  sky130_fd_sc_hdll__mux2_12 _599_ (
    .A0(\mem[6] [7]),
    .A1(data_in[7]),
    .S(_305_),
    .X(_087_)
  );
  sky130_fd_sc_hdll__nor3_1 _600_ (
    .A(_150_),
    .B(wr_ptr[2]),
    .C(_300_),
    .Y(_306_)
  );
  sky130_fd_sc_hdll__mux2_12 _601_ (
    .A0(\mem[9] [0]),
    .A1(data_in[0]),
    .S(_306_),
    .X(_088_)
  );
  sky130_fd_sc_hdll__mux2_12 _602_ (
    .A0(\mem[9] [1]),
    .A1(data_in[1]),
    .S(_306_),
    .X(_089_)
  );
  sky130_fd_sc_hdll__mux2_12 _603_ (
    .A0(\mem[9] [2]),
    .A1(data_in[2]),
    .S(_306_),
    .X(_090_)
  );
  sky130_fd_sc_hdll__mux2_12 _604_ (
    .A0(\mem[9] [3]),
    .A1(data_in[3]),
    .S(_306_),
    .X(_091_)
  );
  sky130_fd_sc_hdll__mux2_12 _605_ (
    .A0(\mem[9] [4]),
    .A1(data_in[4]),
    .S(_306_),
    .X(_092_)
  );
  sky130_fd_sc_hdll__mux2_12 _606_ (
    .A0(\mem[9] [5]),
    .A1(data_in[5]),
    .S(_306_),
    .X(_093_)
  );
  sky130_fd_sc_hdll__mux2_12 _607_ (
    .A0(\mem[9] [6]),
    .A1(data_in[6]),
    .S(_306_),
    .X(_094_)
  );
  sky130_fd_sc_hdll__mux2_12 _608_ (
    .A0(\mem[9] [7]),
    .A1(data_in[7]),
    .S(_306_),
    .X(_095_)
  );
  sky130_fd_sc_hdll__isobufsrc_1 _609_ (
    .A(_298_),
    .SLEEP(_300_),
    .X(_307_)
  );
  sky130_fd_sc_hdll__mux2_12 _610_ (
    .A0(\mem[1] [0]),
    .A1(data_in[0]),
    .S(_307_),
    .X(_096_)
  );
  sky130_fd_sc_hdll__mux2_12 _611_ (
    .A0(\mem[1] [1]),
    .A1(data_in[1]),
    .S(_307_),
    .X(_097_)
  );
  sky130_fd_sc_hdll__mux2_12 _612_ (
    .A0(\mem[1] [2]),
    .A1(data_in[2]),
    .S(_307_),
    .X(_098_)
  );
  sky130_fd_sc_hdll__mux2_12 _613_ (
    .A0(\mem[1] [3]),
    .A1(data_in[3]),
    .S(_307_),
    .X(_099_)
  );
  sky130_fd_sc_hdll__mux2_12 _614_ (
    .A0(\mem[1] [4]),
    .A1(data_in[4]),
    .S(_307_),
    .X(_100_)
  );
  sky130_fd_sc_hdll__mux2_12 _615_ (
    .A0(\mem[1] [5]),
    .A1(data_in[5]),
    .S(_307_),
    .X(_101_)
  );
  sky130_fd_sc_hdll__mux2_12 _616_ (
    .A0(\mem[1] [6]),
    .A1(data_in[6]),
    .S(_307_),
    .X(_102_)
  );
  sky130_fd_sc_hdll__mux2_12 _617_ (
    .A0(\mem[1] [7]),
    .A1(data_in[7]),
    .S(_307_),
    .X(_103_)
  );
  sky130_fd_sc_hdll__nor3_1 _618_ (
    .A(wr_ptr[1]),
    .B(wr_ptr[0]),
    .C(_156_),
    .Y(_308_)
  );
  sky130_fd_sc_hdll__nand3b_1 _619_ (
    .A_N(wr_ptr[2]),
    .B(_308_),
    .C(wr_ptr[3]),
    .Y(_309_)
  );
  sky130_fd_sc_hdll__mux2_12 _620_ (
    .A0(data_in[0]),
    .A1(\mem[8] [0]),
    .S(_309_),
    .X(_104_)
  );
  sky130_fd_sc_hdll__mux2_12 _621_ (
    .A0(data_in[1]),
    .A1(\mem[8] [1]),
    .S(_309_),
    .X(_105_)
  );
  sky130_fd_sc_hdll__mux2_12 _622_ (
    .A0(data_in[2]),
    .A1(\mem[8] [2]),
    .S(_309_),
    .X(_106_)
  );
  sky130_fd_sc_hdll__mux2_12 _623_ (
    .A0(data_in[3]),
    .A1(\mem[8] [3]),
    .S(_309_),
    .X(_107_)
  );
  sky130_fd_sc_hdll__mux2_12 _624_ (
    .A0(data_in[4]),
    .A1(\mem[8] [4]),
    .S(_309_),
    .X(_108_)
  );
  sky130_fd_sc_hdll__mux2_12 _625_ (
    .A0(data_in[5]),
    .A1(\mem[8] [5]),
    .S(_309_),
    .X(_109_)
  );
  sky130_fd_sc_hdll__mux2_12 _626_ (
    .A0(data_in[6]),
    .A1(\mem[8] [6]),
    .S(_309_),
    .X(_110_)
  );
  sky130_fd_sc_hdll__mux2_12 _627_ (
    .A0(data_in[7]),
    .A1(\mem[8] [7]),
    .S(_309_),
    .X(_111_)
  );
  sky130_fd_sc_hdll__or4_1 _628_ (
    .A(_150_),
    .B(wr_ptr[2]),
    .C(_156_),
    .D(_302_),
    .X(_310_)
  );
  sky130_fd_sc_hdll__mux2_12 _629_ (
    .A0(data_in[0]),
    .A1(\mem[10] [0]),
    .S(_310_),
    .X(_112_)
  );
  sky130_fd_sc_hdll__mux2_12 _630_ (
    .A0(data_in[1]),
    .A1(\mem[10] [1]),
    .S(_310_),
    .X(_113_)
  );
  sky130_fd_sc_hdll__mux2_12 _631_ (
    .A0(data_in[2]),
    .A1(\mem[10] [2]),
    .S(_310_),
    .X(_114_)
  );
  sky130_fd_sc_hdll__mux2_12 _632_ (
    .A0(data_in[3]),
    .A1(\mem[10] [3]),
    .S(_310_),
    .X(_115_)
  );
  sky130_fd_sc_hdll__mux2_12 _633_ (
    .A0(data_in[4]),
    .A1(\mem[10] [4]),
    .S(_310_),
    .X(_116_)
  );
  sky130_fd_sc_hdll__mux2_12 _634_ (
    .A0(data_in[5]),
    .A1(\mem[10] [5]),
    .S(_310_),
    .X(_117_)
  );
  sky130_fd_sc_hdll__mux2_12 _635_ (
    .A0(data_in[6]),
    .A1(\mem[10] [6]),
    .S(_310_),
    .X(_118_)
  );
  sky130_fd_sc_hdll__mux2_12 _636_ (
    .A0(data_in[7]),
    .A1(\mem[10] [7]),
    .S(_310_),
    .X(_119_)
  );
  sky130_fd_sc_hdll__nand2_12 _637_ (
    .A(_298_),
    .B(_308_),
    .Y(_311_)
  );
  sky130_fd_sc_hdll__mux2_12 _638_ (
    .A0(data_in[0]),
    .A1(\mem[0] [0]),
    .S(_311_),
    .X(_120_)
  );
  sky130_fd_sc_hdll__mux2_12 _639_ (
    .A0(data_in[1]),
    .A1(\mem[0] [1]),
    .S(_311_),
    .X(_121_)
  );
  sky130_fd_sc_hdll__mux2_12 _640_ (
    .A0(data_in[2]),
    .A1(\mem[0] [2]),
    .S(_311_),
    .X(_122_)
  );
  sky130_fd_sc_hdll__mux2_12 _641_ (
    .A0(data_in[3]),
    .A1(\mem[0] [3]),
    .S(_311_),
    .X(_123_)
  );
  sky130_fd_sc_hdll__mux2_12 _642_ (
    .A0(data_in[4]),
    .A1(\mem[0] [4]),
    .S(_311_),
    .X(_124_)
  );
  sky130_fd_sc_hdll__mux2_12 _643_ (
    .A0(data_in[5]),
    .A1(\mem[0] [5]),
    .S(_311_),
    .X(_125_)
  );
  sky130_fd_sc_hdll__mux2_12 _644_ (
    .A0(data_in[6]),
    .A1(\mem[0] [6]),
    .S(_311_),
    .X(_126_)
  );
  sky130_fd_sc_hdll__mux2_12 _645_ (
    .A0(data_in[7]),
    .A1(\mem[0] [7]),
    .S(_311_),
    .X(_127_)
  );
  sky130_fd_sc_hdll__xnor2_1 _646_ (
    .A(wr_ptr[0]),
    .B(_154_),
    .Y(_312_)
  );
  sky130_fd_sc_hdll__and2_1 _647_ (
    .A(rst_n),
    .B(_312_),
    .X(_128_)
  );
  sky130_fd_sc_hdll__xor2_1 _648_ (
    .A(wr_ptr[1]),
    .B(wr_ptr[0]),
    .X(_313_)
  );
  sky130_fd_sc_hdll__nand2_12 _649_ (
    .A(_153_),
    .B(_313_),
    .Y(_314_)
  );
  sky130_fd_sc_hdll__nand2_12 _650_ (
    .A(wr_ptr[1]),
    .B(_154_),
    .Y(_315_)
  );
  sky130_fd_sc_hdll__a21boi_1 _651_ (
    .A1(_314_),
    .A2(_315_),
    .B1_N(rst_n),
    .Y(_129_)
  );
  sky130_fd_sc_hdll__nand4_1 _652_ (
    .A(wr_ptr[2]),
    .B(wr_ptr[1]),
    .C(wr_ptr[0]),
    .D(_153_),
    .Y(_316_)
  );
  sky130_fd_sc_hdll__o21bai_1 _653_ (
    .A1(_154_),
    .A2(_159_),
    .B1_N(wr_ptr[2]),
    .Y(_317_)
  );
  sky130_fd_sc_hdll__and3_1 _654_ (
    .A(rst_n),
    .B(_316_),
    .C(_317_),
    .X(_130_)
  );
  sky130_fd_sc_hdll__xnor2_1 _655_ (
    .A(wr_ptr[3]),
    .B(_316_),
    .Y(_318_)
  );
  sky130_fd_sc_hdll__and2_1 _656_ (
    .A(rst_n),
    .B(_318_),
    .X(_131_)
  );
  sky130_fd_sc_hdll__o21ai_1 _657_ (
    .A1(rd_ptr[0]),
    .A2(_166_),
    .B1(rst_n),
    .Y(_319_)
  );
  sky130_fd_sc_hdll__a21oi_1 _658_ (
    .A1(rd_ptr[0]),
    .A2(_166_),
    .B1(_319_),
    .Y(_132_)
  );
  sky130_fd_sc_hdll__a21o_6 _659_ (
    .A1(rd_ptr[0]),
    .A2(_166_),
    .B1(rd_ptr[1]),
    .X(_320_)
  );
  sky130_fd_sc_hdll__nand2_12 _660_ (
    .A(rst_n),
    .B(_320_),
    .Y(_321_)
  );
  sky130_fd_sc_hdll__a31oi_1 _661_ (
    .A1(rd_ptr[1]),
    .A2(rd_ptr[0]),
    .A3(_166_),
    .B1(_321_),
    .Y(_133_)
  );
  sky130_fd_sc_hdll__and4_1 _662_ (
    .A(rd_ptr[2]),
    .B(rd_ptr[1]),
    .C(rd_ptr[0]),
    .D(_166_),
    .X(_322_)
  );
  sky130_fd_sc_hdll__a31oi_1 _663_ (
    .A1(rd_ptr[1]),
    .A2(rd_ptr[0]),
    .A3(_166_),
    .B1(rd_ptr[2]),
    .Y(_323_)
  );
  sky130_fd_sc_hdll__nor3b_1 _664_ (
    .A(_322_),
    .B(_323_),
    .C_N(rst_n),
    .Y(_134_)
  );
  sky130_fd_sc_hdll__xnor2_1 _665_ (
    .A(rd_ptr[3]),
    .B(_322_),
    .Y(_324_)
  );
  sky130_fd_sc_hdll__isobufsrc_1 _666_ (
    .A(rst_n),
    .SLEEP(_324_),
    .X(_135_)
  );
  sky130_fd_sc_hdll__nor2_1 _667_ (
    .A(_154_),
    .B(_166_),
    .Y(_325_)
  );
  sky130_fd_sc_hdll__nor2_1 _668_ (
    .A(_153_),
    .B(_167_),
    .Y(_326_)
  );
  sky130_fd_sc_hdll__nand2_12 _669_ (
    .A(_154_),
    .B(_166_),
    .Y(_327_)
  );
  sky130_fd_sc_hdll__nor2_1 _670_ (
    .A(_325_),
    .B(_326_),
    .Y(_328_)
  );
  sky130_fd_sc_hdll__xnor2_1 _671_ (
    .A(count[0]),
    .B(_328_),
    .Y(_329_)
  );
  sky130_fd_sc_hdll__and2_1 _672_ (
    .A(rst_n),
    .B(_329_),
    .X(_136_)
  );
  sky130_fd_sc_hdll__a21o_6 _673_ (
    .A1(_154_),
    .A2(_166_),
    .B1(count[1]),
    .X(_330_)
  );
  sky130_fd_sc_hdll__nand3_1 _674_ (
    .A(count[1]),
    .B(_154_),
    .C(_166_),
    .Y(_331_)
  );
  sky130_fd_sc_hdll__nand3_1 _675_ (
    .A(count[0]),
    .B(_330_),
    .C(_331_),
    .Y(_332_)
  );
  sky130_fd_sc_hdll__a21oi_1 _676_ (
    .A1(_330_),
    .A2(_331_),
    .B1(count[0]),
    .Y(_333_)
  );
  sky130_fd_sc_hdll__nor2_1 _677_ (
    .A(_328_),
    .B(_333_),
    .Y(_334_)
  );
  sky130_fd_sc_hdll__a22oi_1 _678_ (
    .A1(count[1]),
    .A2(_328_),
    .B1(_332_),
    .B2(_334_),
    .Y(_335_)
  );
  sky130_fd_sc_hdll__isobufsrc_1 _679_ (
    .A(rst_n),
    .SLEEP(_335_),
    .X(_137_)
  );
  sky130_fd_sc_hdll__a21boi_1 _680_ (
    .A1(count[0]),
    .A2(_330_),
    .B1_N(_331_),
    .Y(_336_)
  );
  sky130_fd_sc_hdll__nand2_12 _681_ (
    .A(count[2]),
    .B(_326_),
    .Y(_337_)
  );
  sky130_fd_sc_hdll__xnor2_1 _682_ (
    .A(count[2]),
    .B(_326_),
    .Y(_338_)
  );
  sky130_fd_sc_hdll__nor2_1 _683_ (
    .A(_336_),
    .B(_338_),
    .Y(_339_)
  );
  sky130_fd_sc_hdll__a21o_6 _684_ (
    .A1(_336_),
    .A2(_338_),
    .B1(_328_),
    .X(_340_)
  );
  sky130_fd_sc_hdll__nand2_12 _685_ (
    .A(count[2]),
    .B(_328_),
    .Y(_341_)
  );
  sky130_fd_sc_hdll__o21ai_1 _686_ (
    .A1(_339_),
    .A2(_340_),
    .B1(_341_),
    .Y(_342_)
  );
  sky130_fd_sc_hdll__and2_1 _687_ (
    .A(rst_n),
    .B(_342_),
    .X(_138_)
  );
  sky130_fd_sc_hdll__nand2_12 _688_ (
    .A(count[3]),
    .B(_328_),
    .Y(_343_)
  );
  sky130_fd_sc_hdll__o21ai_1 _689_ (
    .A1(_336_),
    .A2(_338_),
    .B1(_337_),
    .Y(_344_)
  );
  sky130_fd_sc_hdll__xnor2_1 _690_ (
    .A(count[3]),
    .B(_327_),
    .Y(_345_)
  );
  sky130_fd_sc_hdll__xnor2_1 _691_ (
    .A(_344_),
    .B(_345_),
    .Y(_346_)
  );
  sky130_fd_sc_hdll__o21ai_1 _692_ (
    .A1(_328_),
    .A2(_346_),
    .B1(_343_),
    .Y(_347_)
  );
  sky130_fd_sc_hdll__and2_1 _693_ (
    .A(rst_n),
    .B(_347_),
    .X(_139_)
  );
  sky130_fd_sc_hdll__nor4_6 _694_ (
    .A(count[3]),
    .B(count[2]),
    .C(_327_),
    .D(_339_),
    .Y(_348_)
  );
  sky130_fd_sc_hdll__and4_1 _695_ (
    .A(count[3]),
    .B(_153_),
    .C(_167_),
    .D(_339_),
    .X(_349_)
  );
  sky130_fd_sc_hdll__o21ai_1 _696_ (
    .A1(_348_),
    .A2(_349_),
    .B1(count[4]),
    .Y(_350_)
  );
  sky130_fd_sc_hdll__o31ai_1 _697_ (
    .A1(count[4]),
    .A2(_348_),
    .A3(_349_),
    .B1(rst_n),
    .Y(_351_)
  );
  sky130_fd_sc_hdll__isobufsrc_1 _698_ (
    .A(_350_),
    .SLEEP(_351_),
    .X(_140_)
  );
  sky130_fd_sc_hdll__nor2_1 _699_ (
    .A(_157_),
    .B(_159_),
    .Y(_352_)
  );
  sky130_fd_sc_hdll__mux2_12 _700_ (
    .A0(\mem[7] [0]),
    .A1(data_in[0]),
    .S(_352_),
    .X(_141_)
  );
  sky130_fd_sc_hdll__mux2_12 _701_ (
    .A0(\mem[7] [1]),
    .A1(data_in[1]),
    .S(_352_),
    .X(_142_)
  );
  sky130_fd_sc_hdll__mux2_12 _702_ (
    .A0(\mem[7] [2]),
    .A1(data_in[2]),
    .S(_352_),
    .X(_143_)
  );
  sky130_fd_sc_hdll__mux2_12 _703_ (
    .A0(\mem[7] [3]),
    .A1(data_in[3]),
    .S(_352_),
    .X(_144_)
  );
  sky130_fd_sc_hdll__mux2_12 _704_ (
    .A0(\mem[7] [4]),
    .A1(data_in[4]),
    .S(_352_),
    .X(_145_)
  );
  sky130_fd_sc_hdll__mux2_12 _705_ (
    .A0(\mem[7] [5]),
    .A1(data_in[5]),
    .S(_352_),
    .X(_146_)
  );
  sky130_fd_sc_hdll__mux2_12 _706_ (
    .A0(\mem[7] [6]),
    .A1(data_in[6]),
    .S(_352_),
    .X(_147_)
  );
  sky130_fd_sc_hdll__mux2_12 _707_ (
    .A0(\mem[7] [7]),
    .A1(data_in[7]),
    .S(_352_),
    .X(_148_)
  );
  sky130_fd_sc_hdll__dfrtp_1 _708_ (
    .CLK(clk),
    .D(_000_),
    .Q(\mem[5] [0]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _709_ (
    .CLK(clk),
    .D(_001_),
    .Q(\mem[5] [1]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _710_ (
    .CLK(clk),
    .D(_002_),
    .Q(\mem[5] [2]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _711_ (
    .CLK(clk),
    .D(_003_),
    .Q(\mem[5] [3]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _712_ (
    .CLK(clk),
    .D(_004_),
    .Q(\mem[5] [4]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _713_ (
    .CLK(clk),
    .D(_005_),
    .Q(\mem[5] [5]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _714_ (
    .CLK(clk),
    .D(_006_),
    .Q(\mem[5] [6]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _715_ (
    .CLK(clk),
    .D(_007_),
    .Q(\mem[5] [7]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _716_ (
    .CLK(clk),
    .D(_008_),
    .Q(\mem[15] [0]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _717_ (
    .CLK(clk),
    .D(_009_),
    .Q(\mem[15] [1]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _718_ (
    .CLK(clk),
    .D(_010_),
    .Q(\mem[15] [2]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _719_ (
    .CLK(clk),
    .D(_011_),
    .Q(\mem[15] [3]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _720_ (
    .CLK(clk),
    .D(_012_),
    .Q(\mem[15] [4]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _721_ (
    .CLK(clk),
    .D(_013_),
    .Q(\mem[15] [5]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _722_ (
    .CLK(clk),
    .D(_014_),
    .Q(\mem[15] [6]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _723_ (
    .CLK(clk),
    .D(_015_),
    .Q(\mem[15] [7]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _724_ (
    .CLK(clk),
    .D(_016_),
    .Q(\mem[4] [0]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _725_ (
    .CLK(clk),
    .D(_017_),
    .Q(\mem[4] [1]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _726_ (
    .CLK(clk),
    .D(_018_),
    .Q(\mem[4] [2]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _727_ (
    .CLK(clk),
    .D(_019_),
    .Q(\mem[4] [3]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _728_ (
    .CLK(clk),
    .D(_020_),
    .Q(\mem[4] [4]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _729_ (
    .CLK(clk),
    .D(_021_),
    .Q(\mem[4] [5]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _730_ (
    .CLK(clk),
    .D(_022_),
    .Q(\mem[4] [6]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _731_ (
    .CLK(clk),
    .D(_023_),
    .Q(\mem[4] [7]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _732_ (
    .CLK(clk),
    .D(_024_),
    .Q(\mem[11] [0]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _733_ (
    .CLK(clk),
    .D(_025_),
    .Q(\mem[11] [1]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _734_ (
    .CLK(clk),
    .D(_026_),
    .Q(\mem[11] [2]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _735_ (
    .CLK(clk),
    .D(_027_),
    .Q(\mem[11] [3]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _736_ (
    .CLK(clk),
    .D(_028_),
    .Q(\mem[11] [4]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _737_ (
    .CLK(clk),
    .D(_029_),
    .Q(\mem[11] [5]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _738_ (
    .CLK(clk),
    .D(_030_),
    .Q(\mem[11] [6]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _739_ (
    .CLK(clk),
    .D(_031_),
    .Q(\mem[11] [7]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _740_ (
    .CLK(clk),
    .D(_032_),
    .Q(\mem[12] [0]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _741_ (
    .CLK(clk),
    .D(_033_),
    .Q(\mem[12] [1]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _742_ (
    .CLK(clk),
    .D(_034_),
    .Q(\mem[12] [2]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _743_ (
    .CLK(clk),
    .D(_035_),
    .Q(\mem[12] [3]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _744_ (
    .CLK(clk),
    .D(_036_),
    .Q(\mem[12] [4]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _745_ (
    .CLK(clk),
    .D(_037_),
    .Q(\mem[12] [5]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _746_ (
    .CLK(clk),
    .D(_038_),
    .Q(\mem[12] [6]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _747_ (
    .CLK(clk),
    .D(_039_),
    .Q(\mem[12] [7]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _748_ (
    .CLK(clk),
    .D(_040_),
    .Q(data_out[0]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _749_ (
    .CLK(clk),
    .D(_041_),
    .Q(data_out[1]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _750_ (
    .CLK(clk),
    .D(_042_),
    .Q(data_out[2]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _751_ (
    .CLK(clk),
    .D(_043_),
    .Q(data_out[3]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _752_ (
    .CLK(clk),
    .D(_044_),
    .Q(data_out[4]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _753_ (
    .CLK(clk),
    .D(_045_),
    .Q(data_out[5]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _754_ (
    .CLK(clk),
    .D(_046_),
    .Q(data_out[6]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _755_ (
    .CLK(clk),
    .D(_047_),
    .Q(data_out[7]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _756_ (
    .CLK(clk),
    .D(_048_),
    .Q(\mem[3] [0]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _757_ (
    .CLK(clk),
    .D(_049_),
    .Q(\mem[3] [1]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _758_ (
    .CLK(clk),
    .D(_050_),
    .Q(\mem[3] [2]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _759_ (
    .CLK(clk),
    .D(_051_),
    .Q(\mem[3] [3]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _760_ (
    .CLK(clk),
    .D(_052_),
    .Q(\mem[3] [4]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _761_ (
    .CLK(clk),
    .D(_053_),
    .Q(\mem[3] [5]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _762_ (
    .CLK(clk),
    .D(_054_),
    .Q(\mem[3] [6]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _763_ (
    .CLK(clk),
    .D(_055_),
    .Q(\mem[3] [7]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _764_ (
    .CLK(clk),
    .D(_056_),
    .Q(\mem[13] [0]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _765_ (
    .CLK(clk),
    .D(_057_),
    .Q(\mem[13] [1]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _766_ (
    .CLK(clk),
    .D(_058_),
    .Q(\mem[13] [2]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _767_ (
    .CLK(clk),
    .D(_059_),
    .Q(\mem[13] [3]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _768_ (
    .CLK(clk),
    .D(_060_),
    .Q(\mem[13] [4]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _769_ (
    .CLK(clk),
    .D(_061_),
    .Q(\mem[13] [5]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _770_ (
    .CLK(clk),
    .D(_062_),
    .Q(\mem[13] [6]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _771_ (
    .CLK(clk),
    .D(_063_),
    .Q(\mem[13] [7]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _772_ (
    .CLK(clk),
    .D(_064_),
    .Q(\mem[14] [0]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _773_ (
    .CLK(clk),
    .D(_065_),
    .Q(\mem[14] [1]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _774_ (
    .CLK(clk),
    .D(_066_),
    .Q(\mem[14] [2]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _775_ (
    .CLK(clk),
    .D(_067_),
    .Q(\mem[14] [3]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _776_ (
    .CLK(clk),
    .D(_068_),
    .Q(\mem[14] [4]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _777_ (
    .CLK(clk),
    .D(_069_),
    .Q(\mem[14] [5]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _778_ (
    .CLK(clk),
    .D(_070_),
    .Q(\mem[14] [6]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _779_ (
    .CLK(clk),
    .D(_071_),
    .Q(\mem[14] [7]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _780_ (
    .CLK(clk),
    .D(_072_),
    .Q(\mem[2] [0]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _781_ (
    .CLK(clk),
    .D(_073_),
    .Q(\mem[2] [1]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _782_ (
    .CLK(clk),
    .D(_074_),
    .Q(\mem[2] [2]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _783_ (
    .CLK(clk),
    .D(_075_),
    .Q(\mem[2] [3]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _784_ (
    .CLK(clk),
    .D(_076_),
    .Q(\mem[2] [4]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _785_ (
    .CLK(clk),
    .D(_077_),
    .Q(\mem[2] [5]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _786_ (
    .CLK(clk),
    .D(_078_),
    .Q(\mem[2] [6]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _787_ (
    .CLK(clk),
    .D(_079_),
    .Q(\mem[2] [7]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _788_ (
    .CLK(clk),
    .D(_080_),
    .Q(\mem[6] [0]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _789_ (
    .CLK(clk),
    .D(_081_),
    .Q(\mem[6] [1]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _790_ (
    .CLK(clk),
    .D(_082_),
    .Q(\mem[6] [2]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _791_ (
    .CLK(clk),
    .D(_083_),
    .Q(\mem[6] [3]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _792_ (
    .CLK(clk),
    .D(_084_),
    .Q(\mem[6] [4]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _793_ (
    .CLK(clk),
    .D(_085_),
    .Q(\mem[6] [5]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _794_ (
    .CLK(clk),
    .D(_086_),
    .Q(\mem[6] [6]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _795_ (
    .CLK(clk),
    .D(_087_),
    .Q(\mem[6] [7]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _796_ (
    .CLK(clk),
    .D(_088_),
    .Q(\mem[9] [0]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _797_ (
    .CLK(clk),
    .D(_089_),
    .Q(\mem[9] [1]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _798_ (
    .CLK(clk),
    .D(_090_),
    .Q(\mem[9] [2]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _799_ (
    .CLK(clk),
    .D(_091_),
    .Q(\mem[9] [3]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _800_ (
    .CLK(clk),
    .D(_092_),
    .Q(\mem[9] [4]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _801_ (
    .CLK(clk),
    .D(_093_),
    .Q(\mem[9] [5]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _802_ (
    .CLK(clk),
    .D(_094_),
    .Q(\mem[9] [6]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _803_ (
    .CLK(clk),
    .D(_095_),
    .Q(\mem[9] [7]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _804_ (
    .CLK(clk),
    .D(_096_),
    .Q(\mem[1] [0]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _805_ (
    .CLK(clk),
    .D(_097_),
    .Q(\mem[1] [1]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _806_ (
    .CLK(clk),
    .D(_098_),
    .Q(\mem[1] [2]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _807_ (
    .CLK(clk),
    .D(_099_),
    .Q(\mem[1] [3]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _808_ (
    .CLK(clk),
    .D(_100_),
    .Q(\mem[1] [4]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _809_ (
    .CLK(clk),
    .D(_101_),
    .Q(\mem[1] [5]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _810_ (
    .CLK(clk),
    .D(_102_),
    .Q(\mem[1] [6]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _811_ (
    .CLK(clk),
    .D(_103_),
    .Q(\mem[1] [7]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _812_ (
    .CLK(clk),
    .D(_104_),
    .Q(\mem[8] [0]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _813_ (
    .CLK(clk),
    .D(_105_),
    .Q(\mem[8] [1]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _814_ (
    .CLK(clk),
    .D(_106_),
    .Q(\mem[8] [2]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _815_ (
    .CLK(clk),
    .D(_107_),
    .Q(\mem[8] [3]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _816_ (
    .CLK(clk),
    .D(_108_),
    .Q(\mem[8] [4]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _817_ (
    .CLK(clk),
    .D(_109_),
    .Q(\mem[8] [5]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _818_ (
    .CLK(clk),
    .D(_110_),
    .Q(\mem[8] [6]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _819_ (
    .CLK(clk),
    .D(_111_),
    .Q(\mem[8] [7]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _820_ (
    .CLK(clk),
    .D(_112_),
    .Q(\mem[10] [0]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _821_ (
    .CLK(clk),
    .D(_113_),
    .Q(\mem[10] [1]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _822_ (
    .CLK(clk),
    .D(_114_),
    .Q(\mem[10] [2]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _823_ (
    .CLK(clk),
    .D(_115_),
    .Q(\mem[10] [3]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _824_ (
    .CLK(clk),
    .D(_116_),
    .Q(\mem[10] [4]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _825_ (
    .CLK(clk),
    .D(_117_),
    .Q(\mem[10] [5]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _826_ (
    .CLK(clk),
    .D(_118_),
    .Q(\mem[10] [6]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _827_ (
    .CLK(clk),
    .D(_119_),
    .Q(\mem[10] [7]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _828_ (
    .CLK(clk),
    .D(_120_),
    .Q(\mem[0] [0]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _829_ (
    .CLK(clk),
    .D(_121_),
    .Q(\mem[0] [1]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _830_ (
    .CLK(clk),
    .D(_122_),
    .Q(\mem[0] [2]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _831_ (
    .CLK(clk),
    .D(_123_),
    .Q(\mem[0] [3]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _832_ (
    .CLK(clk),
    .D(_124_),
    .Q(\mem[0] [4]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _833_ (
    .CLK(clk),
    .D(_125_),
    .Q(\mem[0] [5]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _834_ (
    .CLK(clk),
    .D(_126_),
    .Q(\mem[0] [6]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _835_ (
    .CLK(clk),
    .D(_127_),
    .Q(\mem[0] [7]),
    .RESET_B(1'h1)
  );
  (* src = "fifo.v:21.1-49.4" *)
  sky130_fd_sc_hdll__dfrtp_1 _836_ (
    .CLK(clk),
    .D(_128_),
    .Q(wr_ptr[0]),
    .RESET_B(1'h1)
  );
  (* src = "fifo.v:21.1-49.4" *)
  sky130_fd_sc_hdll__dfrtp_1 _837_ (
    .CLK(clk),
    .D(_129_),
    .Q(wr_ptr[1]),
    .RESET_B(1'h1)
  );
  (* src = "fifo.v:21.1-49.4" *)
  sky130_fd_sc_hdll__dfrtp_1 _838_ (
    .CLK(clk),
    .D(_130_),
    .Q(wr_ptr[2]),
    .RESET_B(1'h1)
  );
  (* src = "fifo.v:21.1-49.4" *)
  sky130_fd_sc_hdll__dfrtp_1 _839_ (
    .CLK(clk),
    .D(_131_),
    .Q(wr_ptr[3]),
    .RESET_B(1'h1)
  );
  (* src = "fifo.v:21.1-49.4" *)
  sky130_fd_sc_hdll__dfrtp_1 _840_ (
    .CLK(clk),
    .D(_132_),
    .Q(rd_ptr[0]),
    .RESET_B(1'h1)
  );
  (* src = "fifo.v:21.1-49.4" *)
  sky130_fd_sc_hdll__dfrtp_1 _841_ (
    .CLK(clk),
    .D(_133_),
    .Q(rd_ptr[1]),
    .RESET_B(1'h1)
  );
  (* src = "fifo.v:21.1-49.4" *)
  sky130_fd_sc_hdll__dfrtp_1 _842_ (
    .CLK(clk),
    .D(_134_),
    .Q(rd_ptr[2]),
    .RESET_B(1'h1)
  );
  (* src = "fifo.v:21.1-49.4" *)
  sky130_fd_sc_hdll__dfrtp_1 _843_ (
    .CLK(clk),
    .D(_135_),
    .Q(rd_ptr[3]),
    .RESET_B(1'h1)
  );
  (* src = "fifo.v:21.1-49.4" *)
  sky130_fd_sc_hdll__dfrtp_1 _844_ (
    .CLK(clk),
    .D(_136_),
    .Q(count[0]),
    .RESET_B(1'h1)
  );
  (* src = "fifo.v:21.1-49.4" *)
  sky130_fd_sc_hdll__dfrtp_1 _845_ (
    .CLK(clk),
    .D(_137_),
    .Q(count[1]),
    .RESET_B(1'h1)
  );
  (* src = "fifo.v:21.1-49.4" *)
  sky130_fd_sc_hdll__dfrtp_1 _846_ (
    .CLK(clk),
    .D(_138_),
    .Q(count[2]),
    .RESET_B(1'h1)
  );
  (* src = "fifo.v:21.1-49.4" *)
  sky130_fd_sc_hdll__dfrtp_1 _847_ (
    .CLK(clk),
    .D(_139_),
    .Q(count[3]),
    .RESET_B(1'h1)
  );
  (* src = "fifo.v:21.1-49.4" *)
  sky130_fd_sc_hdll__dfrtp_1 _848_ (
    .CLK(clk),
    .D(_140_),
    .Q(count[4]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _849_ (
    .CLK(clk),
    .D(_141_),
    .Q(\mem[7] [0]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _850_ (
    .CLK(clk),
    .D(_142_),
    .Q(\mem[7] [1]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _851_ (
    .CLK(clk),
    .D(_143_),
    .Q(\mem[7] [2]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _852_ (
    .CLK(clk),
    .D(_144_),
    .Q(\mem[7] [3]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _853_ (
    .CLK(clk),
    .D(_145_),
    .Q(\mem[7] [4]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _854_ (
    .CLK(clk),
    .D(_146_),
    .Q(\mem[7] [5]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _855_ (
    .CLK(clk),
    .D(_147_),
    .Q(\mem[7] [6]),
    .RESET_B(1'h1)
  );
  sky130_fd_sc_hdll__dfrtp_1 _856_ (
    .CLK(clk),
    .D(_148_),
    .Q(\mem[7] [7]),
    .RESET_B(1'h1)
  );
endmodule
